site_name: My Documentation
site_description: Documentation site with version support
site_author: Your Name
site_url: https://kanzifucius.github.io/mkdocs-gh-pages/

# Repository
repo_name: kanzifucius/mkdocs-gh-pages
repo_url: https://github.com/kanzifucius/mkdocs-gh-pages
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md

# Mike versioning
extra:
  version:
    provider: mike